typography_spectrum: 0.6616698403377086
color:
  brandStrength: 0.04494722653180361
  lightness: 0.3985719420015812
  saturation: 0.041420076973736286
  rhythmicContrast: 0.774396585766226
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.695277814520523
author:
  name: Cassie Giles
  email: cassie@sprinklesparty.com
  url: www.sprinklesparty.com
name: Sprinkles Party Co.
title: get ready to throw some confetti...
